#!/usr/bin/env python3
"""
Read results/raw/threeway_v2_*_fw.csv and generate a LaTeX file with
one table per outcome (weighted). Each table shows IV and OLS columns
with var3/var4/var5 rows.

Output: results/cleaned/threeway_v2_outcome_tables_weighted.tex
"""
import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RES = ROOT / "results"
RAW = RES / "raw"
OUT_DIR = RES / "cleaned"
OUT_TEX = OUT_DIR / "threeway_v2_outcome_tables_weighted.tex"

FILES = [
    ("share_new_msa", "Share of hires in new MSA (weighted)"),
    ("share_remote", "Share of hires remote (weighted)"),
    ("total_dispersion", "Total dispersion (new + remote), weighted"),
]

def load_csv(path):
    with path.open() as f:
        r = csv.DictReader(f)
        return list(r)

def fmt(x):
    return f"{float(x):.3f}"

def stars(pval):
    try:
        p = float(pval)
    except Exception:
        return ""
    if p < 0.01:
        return "***"
    if p < 0.05:
        return "**"
    if p < 0.10:
        return "*"
    return ""

def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    lines = []
    lines.append("% Auto-generated by py/create_threeway_v2_outcome_tables_weighted.py\n")
    for stem, title in FILES:
        path = RAW / f"threeway_v2_{stem}_fw.csv"
        if not path.exists():
            continue
        rows = load_csv(path)
        lines.append("\\begin{table}[htbp]\n")
        lines.append("  \\centering\n")
        lines.append(f"  \\caption{{{title}}}\n")
        lines.append(f"  \\label{{tab:{stem}_fw}}\n")
        by_model = {r["model"].strip(): r for r in rows}
        lines.append("  \\begin{threeparttable}\n")
        lines.append("  \\begin{adjustbox}{max width=\\textwidth}\n")
        lines.append("  \\begin{tabular}{lcc}\n")
        lines.append("    \\toprule\n")
        lines.append("    Variable & OLS & IV \\\\ \n")
        lines.append("    \\midrule\n")
        def coef_val(model_key, coef_key):
            rec = by_model.get(model_key)
            if not rec:
                return "--"
            p_key = coef_key.replace("coef_", "p_")
            return f"{fmt(rec[coef_key])}{stars(rec.get(p_key))}"
        def se_val(model_key, se_key):
            rec = by_model.get(model_key)
            if not rec:
                return "--"
            return f"({fmt(rec[se_key])})"
        var_names = {
            'var3': '$ \\text{Remote} \\times \\mathds{1}(\\text{Post}) $',
            'var4': '$ \\mathds{1}(\\text{Post}) \\times \\text{Startup} $',
            'var5': '$ \\text{Remote} \\times \\mathds{1}(\\text{Post}) \\times \\text{Startup} $',
        }
        lines.append(f"    {var_names['var3']} & {coef_val('OLS','coef_v3')} & {coef_val('IV','coef_v3')} \\\\ \n")
        lines.append(f"     & {se_val('OLS','se_v3')} & {se_val('IV','se_v3')} \\\\ \n")
        lines.append("    \\addlinespace[0.5em]\n")
        lines.append(f"    {var_names['var4']} & {coef_val('OLS','coef_v4')} & {coef_val('IV','coef_v4')} \\\\ \n")
        lines.append(f"     & {se_val('OLS','se_v4')} & {se_val('IV','se_v4')} \\\\ \n")
        lines.append("    \\addlinespace[0.5em]\n")
        lines.append(f"    {var_names['var5']} & {coef_val('OLS','coef_v5')} & {coef_val('IV','coef_v5')} \\\\ \n")
        lines.append(f"     & {se_val('OLS','se_v5')} & {se_val('IV','se_v5')} \\\\ \n")
        n_ols = by_model.get('OLS', {}).get('N', '--')
        n_iv  = by_model.get('IV',  {}).get('N', '--')
        m_ols = by_model.get('OLS', {}).get('depmean', None)
        m_iv  = by_model.get('IV',  {}).get('depmean', None)
        kpf   = by_model.get('IV',  {}).get('kpf', '--')
        lines.append("    \\addlinespace\\n")
        lines.append(f"    N & {n_ols} & {n_iv} \\\\ \n")
        if m_ols is not None and m_iv is not None:
            lines.append(f"    Mean dep. var. & {fmt(m_ols)} & {fmt(m_iv)} \\\\ \n")
        lines.append(f"    KP rk Wald F & -- & {kpf} \\\\ \n")
        lines.append("    \\bottomrule\n")
        lines.append("  \\end{tabular}\n")
        lines.append("  \\end{adjustbox}\n")
        lines.append("  \\end{threeparttable}\n")
        lines.append("\\end{table}\n\n")

    OUT_TEX.write_text("".join(lines))
    print(f"Wrote {OUT_TEX}")

if __name__ == "__main__":
    main()

