#!/usr/bin/env python3
"""
Create a LaTeX summary table (weighted) from results/threeway_v2_results_fw.csv.

Output: results/cleaned/threeway_v2_results_weighted.tex
Columns: Outcome | IV (coef, SE) | OLS (coef, SE)
"""
import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RES = ROOT / "results"
RAW_CSV = RES / "threeway_v2_results_fw.csv"
OUT_DIR = RES / "cleaned"
OUT_TEX = OUT_DIR / "threeway_v2_results_weighted.tex"

ORDER = [
    "New_MSA",
    "Remote",
    "Total_Dispersion",
    "Legacy_MSA",
]
LABELS = {
    "New_MSA": "New MSA",
    "Remote": "Remote",
    "Total_Dispersion": "Total dispersion",
    "Legacy_MSA": "Legacy MSA",
}

def fmt(c: float, se: float, p: float | None = None) -> str:
    s = ""
    if p is not None:
        try:
            if p < 0.01:
                s = "***"
            elif p < 0.05:
                s = "**"
            elif p < 0.10:
                s = "*"
        except Exception:
            s = ""
    return f"{c:.3f}{s} ({se:.3f})"

def main():
    if not RAW_CSV.exists():
        raise SystemExit(f"Missing results CSV: {RAW_CSV}")

    rows = []
    with RAW_CSV.open() as f:
        r = csv.DictReader(f)
        for d in r:
            rows.append({
                "model": d["model"].strip(),
                "outcome": d["outcome"].strip(),
                "coef": float(d["coef"]),
                "se": float(d["se"]),
                "p": float(d.get("p", "nan")) if d.get("p") not in (None, "") else None,
            })

    per_outcome = {}
    for rec in rows:
        per_outcome.setdefault(rec["outcome"], {})[rec["model"]] = (rec["coef"], rec["se"], rec.get("p"))

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    lines = []
    lines.append("% Auto-generated by py/create_threeway_v2_table_weighted.py\n")
    lines.append("\\begin{table}[htbp]\n")
    lines.append("  \\centering\n")
    lines.append("  \\caption{Three-way geographic hiring shares (weighted): IV and OLS estimates (var3)}\n")
    lines.append("  \\label{tab:threeway_v2_weighted}\n")
    lines.append("  \\begin{tabular}{lcc}\n")
    lines.append("    \\toprule\n")
    lines.append("    Outcome & IV & OLS \\\\ \n")
    lines.append("    \\midrule\n")
    for key in ORDER:
        if key not in per_outcome:
            continue
        iv = per_outcome[key].get("IV")
        ols = per_outcome[key].get("OLS")
        iv_s = fmt(iv[0], iv[1], iv[2]) if iv else "--"
        ols_s = fmt(ols[0], ols[1], ols[2]) if ols else "--"
        lines.append(f"    {LABELS.get(key, key)} & {iv_s} & {ols_s} \\\\ \n")
    lines.append("    \\bottomrule\n")
    lines.append("  \\end{tabular}\n")
    lines.append("\\end{table}\n")

    OUT_TEX.write_text("".join(lines))
    print(f"Wrote {OUT_TEX}")

if __name__ == "__main__":
    main()

